### ISSUE TITLE
When do you plan to switch to SPV(BIP157, BIP158) mode?

### ISSUE THREAD

**Issue by evgeniy-scherbina** [rust-bitcoin/rust-bitcoin-spv#16]
It seems that it just download whole blockchain and does not expose any API to work with it in SPV mode?
I'm interested how soon do you plan to switch to spv mode?
Maybe I can help with it?

**Comment by tamasblummer** [comment]
The complete download was a temporary situation used to test Hammersbald integration. I plan to implement a BIP158 server and client within the coming weeks. Thereafter this will only download header in client mode and full blocks that match BIP158 filter. Server mode will compute and serve filters.
